### PR TITLE
Updated Style and Functions

### PR DESCRIPTION
**Pull request by thehappydinoa**
- Simplified Code
- Changed `wget` to `urlretrieve`
- Added Shebang
- Added argparse
- Added configparse

### CODE REVIEW

**Comment by omergunal** [comment]
Hi, thanks for your contribution. i taken this error
a

**Comment by thehappydinoa** [comment]
@omergunal I fixed this, thank you so much for finding this. I cannot believe I missed that.

**Comment by omergunal** [comment]
Thanks for your effort

**Comment by thehappydinoa** [comment]
Thank you

**Pull request merged**
